import { Lato } from "next/font/google";
import AuthProvider from "@/components/SessionProvider"; // Import the client wrapper
import "./globals.css";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";


import connectDB from "@/lib/mongodb";

const lato = Lato({
  variable: "--font-lato",
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"], // Specify the weights you need
});

export const metadata = {
  title: "X. It’s what’s happening / X",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const conn = connectDB(); // Universally connect DB
  const session = await getServerSession(authOptions); // Get session server-side
  return (
    <html lang="en">
      <body className={lato.variable}>
      <AuthProvider session={session}>
          {children} 
        </AuthProvider>
      </body>
    </html>
  );
}
